# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
[project]
name = "cloudflared-operator-monorepo"
version = "0.1.0"
requires-python = ">=3.12"
readme = "README.md"
[dependency-groups]
fmt = [ "ruff" ]
lint = [
  "codespell",
  "jubilant==1.10.0",
  "mypy",
  "ops[testing]",
  "pep8-naming",
  "pytest",
  "pytest-asyncio",
  "pytest-operator",
  "requests",
  "ruff",
  "types-pyyaml",
  "types-requests",
]
integration = [
  "allure-pytest>=2.8.18",
  "allure-pytest-collection-report @ git+https://github.com/canonical/data-platform-workflows@v24.0.0#subdirectory=python/pytest_plugins/allure_pytest_collection_report",
  "jubilant==1.10.0",
  "pytest",
  "pytest-asyncio",
  "pytest-operator",
]
[tool.uv]
package = false
[tool.codespell]
skip = "charmed-cloudflared-snap,cloudflare-configurator-operator,cloudflared-operator"
